sonar.projectKey=slidesk_slidesk
sonar.organization=slidesk
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=src/templates/**,.github/**,src/core/babelfish/replaceWithTemplate.ts,src/core/tcpserver/ansi.ts,src/core/tcpserver/parse.ts,src/core/babelfish/treatSlide.ts
sonar.cpd.exclusions=**/*.test.ts,src/commands/**
sonar.coverage.exclusions=src/commands/**,src/index.ts,**/*.test.ts,src/core/tcpserver/**,src/core/server/**,src/core/*.ts,src/utils/save.ts,src/utils/interactCLI.ts,src/utils/convert.ts
