sonar.projectKey=slidesk_slidesk
sonar.organization=slidesk
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=src/templates/**,.github/**
sonar.cpd.exclusions=**/*.test.ts,src/commands/**
sonar.coverage.exclusions=src/commands/**,src/index.ts,**/*.test.ts
