sonar.projectKey=slidesk_slidesk
sonar.organization=slidesk
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=src/command/*.ts,example/**/*.*,src/templates/**/*.*,src/index.ts
sonar.exclusions=example/**/*.*
